#!/bin/sh

#Install brew & oh-my-zsh first
#Install fonts

brew install ack wget tree bat exa fzf diff-so-fancy macvim
mkdir ~/.tmp
mkdir ~/.vim
ln -s `pwd`/zshrc ~/.zshrc
ln -s `pwd`/p10k.zsh ~/.p10k.zsh

ln -s `pwd`/vimrc ~/.vimrc
ln -s `pwd`/gvimrc ~/.gvimrc
ln -s `pwd`/ackrc ~/.ackrc

ln -s `pwd`/gitconfig ~/.gitconfig
