#!/bin/sh

brew install ack wget tree bat exa fzf diff-so-fancy macvim
mkdir ~/.tmp
mkdir ~/.vim
ln -s ~/.dotfiles/zshrc ~/.zshrc
ln -s ~/.dotfiles/vimrc ~/.vimrc
ln -s ~/.dotfiles/gvimrc ~/.gvimrc
ln -s ~/.dotfiles/ackrc ~/.ackrc
ln -s ~/.dotfiles/vim-syntax ~/.vim/syntax
ln -s ~/.dotfiles/vim-indent ~/.vim/indent
